version: '3'
services:
  jenkins:
    image: angpao/jenkins:2.156-install-libltdl7
    container_name: jenkins
    user: 'root'
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /opt/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
  
